const ADD_GUEST = 'ADD_GUEST'
const REMOVE_GUEST = 'REMOVE_GUEST'
const VIEW_CHANGE = 'VIEW_CHANGE'
const VIEW_PROFILE = 'VIEW_PROFILE'
const EDIT_NAMETAG = 'EDIT_NAMETAG'
const NAMETAG_CHANGE = 'NAMETAG_CHANGE'
const NAMETAG_SAVE = 'NAMETAG_SAVE'
const ADD_NAMETAG = 'ADD_NAMETAG'


export {
  ADD_GUEST,
  REMOVE_GUEST,
  VIEW_CHANGE,
  VIEW_PROFILE,
  EDIT_NAMETAG,
  NAMETAG_CHANGE,
  NAMETAG_SAVE,
  ADD_NAMETAG
}
